### ISSUE TITLE
Executable installed with go install show "version source" with -v option

### ISSUE THREAD

**Issue by luckv** [bvieira/sv4git#33]
I installed and updated the tool with `go install github.com/bvieira/sv4git/v2/cmd/git-sv@latest`
which I prefer because I can update the tool more easily than downloading it from the browser and placing manuelly in the bin directory.

But if I launch `git sv -v` the tool outputs the default `sv version source` when no version is provided.

The binary downloaded from github doesn't have this problem and outputs correctly the version.

**Comment by bvieira** [comment]
Hello,

This behavior is expected, the version is added during compiling time using `ldflags`. When you use go install, it compiles from source without any flag.

It's possible to set the flag using go install:

```bash
VERSION=$(go list -f '{{ .Version }}' -m -versions github.com/bvieira/sv4git/v2 | sed 's/v//') go install --ldflags "-X main.Version=$VERSION" gi
thub.com/bvieira/sv4git/v2/cmd/git-sv@v$VERSION
```

What do you think?

**Comment by luckv** [comment]
The command doesn't work on my machine. The version parsed is an empty string.
I'm on mac os 11.4 and try with both zsh and bash 3.2

**Comment by bvieira** [comment]
sorry, add `&&` between the commands..

```bash
VERSION=$(go list -f '{{ .Version }}' -m -versions github.com/bvieira/sv4git/v2 | sed 's/v//') && go install --ldflags "-X main.Version=$VERSION" github.com/bvieira/sv4git/v2/cmd/git-sv@v$VERSION
```

**Comment by luckv** [comment]
Doesn't work. The shell variable `VERSION` is empty
If I run
```VERSION=$(go list -f '{{ .Version }}' -m -versions github.com/bvieira/sv4git/v2 | sed 's/v//') && echo \"$VERSION\"```
I expect to see in the terminal output:
`"2.5.0"`
but what I see is:
`""`
Tested both with zsh and bash

**Comment by bvieira** [comment]
> The problem is the format `.Version`, using: 
> `go list -f '{{ .Version }}' -m -versions github.com/bvieira/sv4git/v2` returns an empty string 
> but 
> `go list -f '{{ .Versions }}' -m -versions github.com/bvieira/sv4git/v2` returns the versions in square brackets

I dont know why, but the version is empty for you.. I tried on linux and it returns right, then I tried on windows and the version is empty.. but if you add `@latest`, it works.. can you try running with latest?

```bash
go list -json -m -versions github.com/bvieira/sv4git/v2@latest
```

Result on windows:

```bash
PS C:\Users\bvieira> go list -json -m -versions github.com/bvieira/sv4git/v2
{
        "Path": "github.com/bvieira/sv4git/v2",
        "Versions": [
                "v2.0.0",
                "v2.1.0",
                "v2.1.1",
                "v2.2.0",
                "v2.2.1",
                "v2.3.0",
                "v2.4.0",
                "v2.5.0"
        ]
}

PS C:\Users\bvieira> go list -json -m -versions github.com/bvieira/sv4git/v2@latest
{
        "Path": "github.com/bvieira/sv4git/v2",
        "Version": "v2.5.0",
        "Versions": [
                "v2.0.0",
                "v2.1.0",
                "v2.1.1",
                "v2.2.0",
                "v2.2.1",
                "v2.3.0",
                "v2.4.0",
                "v2.5.0"
        ],
        "Time": "2021-09-24T21:48:20Z",
        "GoMod": "C:\\Users\\bvieira\\go\\pkg\\mod\\cache\\download\\github.com\\bvieira\\sv4git\\v2\\@v\\v2.5.0.mod",
        "GoVersion": "1.16"
}
```

**Comment by bvieira** [comment]
ahh.. it seams that you can use go list without versions, maybe it's better..

```bash
go list -f '{{ .Version }}' -m  github.com/bvieira/sv4git/v2@latest
```

**Comment by luckv** [comment]
Fantastic, it works!
The correct command it's:
```
VERSION=$(go list -f '{{ .Version }}' -m github.com/bvieira/sv4git/v2@latest | sed 's/v//') && go install --ldflags "-X main.Version=$VERSION" github.com/bvieira/sv4git/v2/cmd/git-sv@v$VERSION
```
