### ISSUE TITLE
[Feature Request] Allow regex to select part of commit message for conventional parsing

### ISSUE THREAD

**Issue by hypervtechnics** [bvieira/sv4git#44]
Hi,

sorry to bother you again. I encountered a scenario where our SCM system prepends the PR merge commits with `Merged PR xxx: <the original title>`. It would be nice to have some kind of parsing preprocessor to select only a certain part from a commit message to parse for conventional commit format.

In my case this would look like this:

`(Merged PR \d+): (?P<message>.*)`

![grafik](https://user-images.githubusercontent.com/10027956/156181702-b34c14f7-3124-44bb-afac-c19e7d468e78.png)

By default this could be `(?P<message>.*)` to just select the whole thing. Or this step could be completly skipped if the pattern is empty.

**Comment by hypervtechnics** [comment]
@bvieira I started working on [!45](https://github.com/bvieira/sv4git/pull/45) could you have a look? :)

**Comment by hypervtechnics** [comment]
You there? @bvieira

**Comment by bvieira** [comment]
> You there? @bvieira

@hypervtechnics  sorry for the late reply.. im going to take a look this week
