### ISSUE TITLE
Running commands after install in Ubuntu results in an error. 

### ISSUE THREAD

**Issue by donjmilligan** [bvieira/sv4git#53]
when I run commands such as `git sv cfg show` or `git sv cfg default` I get the following error:

`/home/myuser/bin/git-sv: 1: Syntax error: "(" unexpected`

Running `git-sv` results in the following error:

`bash: /home/descere/bin/git-sv: cannot execute binary file: Exec format error`

I'm not sure that it matters, but I have run these commands both with a .sv4git.yml file in my repository and without it. Both get the same result 

OS: Ubuntu 20.04

**Comment by bvieira** [comment]
hey @donjmilligan, sorry for only seeing this right now.. which version are you using?

**Comment by bvieira** [comment]
im going to close this.. feel free to open it again if you still have any problem..

I tested on linux mint and it's working fine.. could it be that you got the `arm64` binnary instead of the `amd64`?
