### ISSUE TITLE
Request: changelog from a commit/date ?

### ISSUE THREAD

**Issue by syrm** [bvieira/sv4git#7]
Hello,

Could you add a feature to generate a changelog from a commit or a date ?
We are doing continuous delivery, we don't tag each commit on master.

But we want to be able to sumup the modifications during a period.

**Comment by bvieira** [comment]
Hello there,

Tagging each commit don't seems to be a good idea, but it would be recommended to create a tag every time you release your application.

Every time you merge a branch on master (and that branch could have on or more commits), your CI would build your project generating a new release (version and tag) to be deployed by your CD.

I suppose it would be possible to create a new action that act like `release-notes` and expects a `start` and `end` date, but it's not possible to calculate a version, it would look like:

```bash
$ git sv period-changes --start 2020-01-01 --end 2020-01-05
## 2021-01-01 ~ 2021-01-05

### Bug Fixes

- commit1 (2e9dce7)
- commit2 (eefdf6c)
```

Either `changelog` and `release-notes` are related with release, I think it would be weird to use them without a version

**Comment by syrm** [comment]
The release is automatic for each commit/merge on master, so its like tagging each commit on master, we won't do that.

Yes something like that without a version is fine, specialy if it work with hash too

**Comment by bvieira** [comment]
@syrm, I made the changes so it would be possible to generate notes using a commit range. Could you check if this is what you are expecting?

The generated notes have the same behavior of `release-notes` and `changelog` using the range instead of tag. The date on top is the date of the last/newer commit.

**commit-log**

```bash
$ git sv commit-log --range hash --start 6c2039a~1
{"date":"2021-01-25","hash":"a6df032","type":"docs","subject":"add range section","body":"issue: #7","metadata":{"issueid":"#7"}}
{"date":"2021-01-25","hash":"741962b","type":"refactor","subject":"change start and end descriptions","body":"issue: #7","metadata":{"issueid":"#7"}}
{"date":"2021-01-25","hash":"3652c52","type":"docs","subject":"fix commit-notes alias on readme","body":"issue: #7","metadata":{"issueid":"#7"}}
{"date":"2021-01-25","hash":"1d0a777","type":"docs","subject":"add commit-notes on readme","body":"issue: #7","metadata":{"issueid":"#7"}}
{"date":"2021-01-25","hash":"997c604","type":"refactor","subject":"change commit-notes description"}
{"date":"2021-01-25","hash":"a6259a9","type":"feat","subject":"add commit-notes action","body":"issue: #7","metadata":{"issueid":"#7"}}
{"date":"2021-01-25","hash":"8b57bee","type":"refactor","subject":"better description on commit-log"}
{"date":"2021-01-25","hash":"41be35e","type":"feat","subject":"add range and date at commit log action","body":"related to #7"}
{"date":"2020-12-02","hash":"02fce48","subject":"Merge pull request #6 from bvieira/commit","body":"Feature: commit command"}
{"date":"2020-12-02","hash":"6c2039a","type":"test","subject":"add tests for message issueID and format"}
```

**commit-notes**

```bash
$ git sv commit-notes --range hash --start 6c2039a~1
## 2021-01-25

### Features

- add commit-notes action (a6259a9) (#7)
- add range and date at commit log action (41be35e)

```

**Comment by syrm** [comment]
Clearly, PERFECT !

You're awesome, thank you a lot.
