### ISSUE TITLE
[Feature Request] Support environment variables in template

### ISSUE THREAD

**Issue by serebro** [bvieira/sv4git#87]
Hi,
sv4git is a great tool, thank you

As I see template does not support environment variables. It is why I cannot to build some links in changelog, for example a link to commit in GitHub or GitLab because I do not have a name of organization, project name and so on.

I found that this can be solved very easily.
It would be enough [here](https://github.com/bvieira/sv4git/blob/master/sv/formatter.go#L37) to add one line `"getenv":     os.Getenv` to have something like this
```go
	templateFNs := map[string]interface{}{
		"timefmt":    timeFormat,
		"getsection": getSection,
		"getenv":     os.Getenv,
	}
```

**Comment by bvieira** [comment]
Hey, thanks for using sv4git :heart: !!

This was a very simple one, thanks for pointing it out.. it's available on [v2.9.0](https://github.com/bvieira/sv4git/releases/tag/v2.9.0) :rocket: !!

Just let me know if it's working as expected!!
